name: "ğŸŒ Environment"
description: "Development environment settings"
labels: "ğŸŒ Environment"
body:
  - type: textarea
    attributes:
      label: ğŸŒ Describe
      description: ëª©ì 
    validations:
      required: true
  - type: textarea
    attributes:
      label: âœ… Tasks
      description: ì—…ë¬´ ì„¸ë¶„í™”
    validations:
      required: true
  - type: textarea
    attributes:
      label: ğŸ’¬ Additional context
      description: ì¶”ê°€ ë‚´ìš©
